# Generated by Django 6.0.6 on 2026-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
