# Generated by Django 6.1 on 2026-09-09 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_category_options'),
        ('userpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity', models.IntegerField(default=1)),
                ('payement_method', models.CharField(choices=[('cash', 'Cash On Delivery'), ('esewa', 'Esewa'), ('khalti', 'Khalti')], default='cash')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('way', 'On your Way'), ('delivered', 'Delivered')], default='pending')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
