# Generated by Django 6.1 on 2026-09-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_alter_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
    ]
