# Generated by Django 6.1 on 2026-09-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0005_remove_order_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payement_method',
            new_name='payment_method',
        ),
    ]
